const ACTION_CHANGE_USER_INFO = 'ACTION_CHANGE_USER_INFO';
const ACTION_CHANGE_NAVBAR_NAME = 'ACTION_CHANGE_NAVBAR_NAME';
const ACTION_CHANGE_UUID = 'ACTION_CHANGE_UUID';
const KEY_USER_DATA = 'SET_USER_DATA';
const KEY_UUID = 'SET_UUID';
export {
  KEY_USER_DATA,
  ACTION_CHANGE_UUID,
  KEY_UUID,
  ACTION_CHANGE_USER_INFO,
  ACTION_CHANGE_NAVBAR_NAME,
};
